### ISSUE TITLE
clang no longer builds libco/amd64_gcc.c

### ISSUE THREAD

**Issue by devinacker** [awjackson/bsnes-classic#4]
It seems that llvm made some changes w/r/t what is allowed to be done in naked functions:
http://llvm.org/viewvc/llvm-project?view=revision&revision=217199
http://llvm.org/viewvc/llvm-project?view=revision&revision=217200

As a result, people reported that newer versions of xcode/clang now emit errors when building amd64_gcc.c:

```
clang++ -xc -std=gnu99 -I. -Isnes -O3 -fomit-frame-pointer -DNDEBUG -march=native -DNDEBUG -Wno-switch -Wno-absolute-value -Wno-parentheses -march=native -DPROFILE_COMPATIBILITY -DDEBUGGER -c libco/libco.c -o obj/libco.o
In file included from libco/libco.c:22:
libco/amd64_gcc.c:135:17: error: parameter references not allowed in naked functions
    : [to] "r" (to), [from] "r" (from)
                ^
libco/amd64_gcc.c:66:6: note: attribute is here
void NAKED co_switch(cothread_t to) {
     ^
libco/amd64_gcc.c:61:34: note: expanded from macro 'NAKED'
    #define NAKED __attribute__((naked))
                                 ^
libco/amd64_gcc.c:67:3: error: non-ASM statement in naked function is not supported
  register cothread_t from __asm__("rdx") = co_active_handle;
  ^
libco/amd64_gcc.c:66:6: note: attribute is here
void NAKED co_switch(cothread_t to) {
     ^
libco/amd64_gcc.c:61:34: note: expanded from macro 'NAKED'
    #define NAKED __attribute__((naked))
                                 ^
```

I advised defining LIBCO_NO_INLINE_ASM as a temporary workaround, but I'm not familiar enough with llvm/clang (or inline asm semantics in general) to know if there's a simple enough fix that'll still let the same file be built with clang and gcc.

(cc @optiroc, @carterli)

**Comment by awjackson** [comment]
Looks like I'm going to have to bite the bullet and use file-scope inline asm after all.

**Comment by Optiroc** [comment]
My fork compiles with clang 7.0, but it includes some stuff brought in from the mercury fork…

https://github.com/devinacker/bsnes-plus/compare/master...Optiroc:master https://github.com/devinacker/bsnes-plus/compare/master...Optiroc:master

Most diffs are just due to Sublime Text’s whitespace-stripping and formatting, and libco/armeabi.c isn’t compiled for x64 obviously. The only meaningful change I can see otherwise is the signature of co_active():

-cothread_t co_active();
+cothread_t co_active(void);

-David

**Comment by awjackson** [comment]
I'm now using file-scope inline asm, which is uglier but should be safer. It's tested on Linux and 32-bit Windows, the only platforms I'm able to compile on, but I _think_ I've done things correctly for 64-bit Windows and for OSX as well. Please open a new issue if bsnes fails to compile, link or run on any platform.

**Comment by devinacker** [comment]
Looks okay on 64-bit Windows as well.
